### ISSUE TITLE
eval/inference.py not available

### ISSUE THREAD

**Issue by XinAn9508** [sejong-rcv/PVLR#1]
Hello, I am currently exploring your paper "Probabilistic Vision-Language Representation for Weakly Supervised Temporal Action Localization," and I find it incredibly intriguing!

I noticed that the eval/inference.py code mentioned in the README is not available in the repository. If possible, could you please consider making it open source? It would be very helpful for those of us looking to understand and utilize the project fully.

Thank you for your time and for the great work you’re doing!

**Comment by LimGeunTaekk** [comment]
Sorry for the late reply. I was occupied with other schedules.

I noticed that the eval/inference.py file was missing, so I have uploaded it now.

If there are any other issues, feel free to reach out to me.

I really appreciate your interest.

**Comment by LimGeunTaekk** [comment]
https://github.com/sejong-rcv/PVLR/blob/main/src/thumos/eval/inference.py

https://github.com/sejong-rcv/PVLR/blob/main/src/anet/eval/inference.py
